export const GIFTCARDS_LOADING = 'GIFTCARDS_LOADING';
export const ADD_GIFTCARDS = 'ADD_GIFTCARDS';
export const GIFTCARDS_FAILED = 'GIFTCARDS_FAILED';

export const ADVERTISEMENTS_LOADING = 'ADVERTISEMENTS_LOADING';
export const ADD_ADVERTISEMENTS = 'ADD_ADVERTISEMENTS';
export const ADVERTISEMENTS_FAILED = 'ADVERTISEMENTS_FAILED';
